---
title: "DATA 608 Assignment 3 - Question 1"
author: "Nathaniel Cooper"
date: "October 4, 2018"
output: 
  html_document:
    code_folding: hide
runtime: shiny    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, rlib, eval=TRUE, include=FALSE}
library(shiny)
library(tidyverse)
library(plotly)
library(rsconnect)
library(RCurl)
Sys.setenv("plotly_username"='********************')
Sys.setenv("plotly_api_key"='***********************')
rsconnect::setAccountInfo(name='*********************',
			  token='***********************',
			  secret='**********************')
#rsconnect::deployApp('~/R_Scripts/shinyapp')
```

```{r, data, eval=TRUE, include=FALSE}
#needed to load data from github so the shiny app would work on the webpage
data_url <- getURL('https://raw.githubusercontent.com/charleyferrari/CUNY_DATA_608/master/module3/data/cleaned-cdc-mortality-1999-2010-2.csv')
mortality_data <- read_csv(data_url)
#head(mortality_data)
#summary(mortality_data)
```
```{r, init_vis, eval=FALSE, include=FALSE}
#Some Data visualzations I did to see what the data was like
hist(mortality_data$Deaths)
hist(mortality_data$Population)
hist(mortality_data$Year)
```

```{r, filtr, eval=TRUE, include=FALSE}
#subsetting the data
mental_data_2010 <- filter(mortality_data, Year == 2010 & ICD.Chapter == 'Mental and behavioural disorders')
mental_data_2010 <-  mental_data_2010 %>% arrange(Crude.Rate)
#head(mental_data_2010)
```

```{r, bar_plots, eval=TRUE, include=FALSE}
#tested the plot by publsihing to my plotly page
p <- plot_ly(x = mental_data_2010$Crude.Rate, y = mental_data_2010$State, type = 'bar', text = mental_data_2010$Crude.Rate, textposition = 'auto',  color = I("grey"), orientation = 'h')

# Create a shareable link to your chart
# Set up API credentials: https://plot.ly/r/getting-started
#chart_link = api_create(p, filename="horizontalbar-Mental_Health_Mortality")
#chart_link
```

```{r, shny_ui, eval=TRUE}
#Adapted from https://plot.ly/r/shiny-tutorial/
ui <-# Use a fluid Bootstrap layout
fluidPage(    
  plotlyOutput("plot"),
  verbatimTextOutput("event")
)
```

```{r shny_server, eval=TRUE}
#Adapted from https://plot.ly/r/shiny-tutorial/
server <- function(input, output) {
  
  output$plot <- renderPlotly({
    p #used the above plotly object instead of redoing here
  })
    output$event <- renderPrint({
    d <- event_data("plotly_hover")
    if (is.null(d)) "Hover on a bar to see State Data!" else d
  })
}

shinyApp(ui, server, options = list(height = 540, width = 960))
```
